name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: npx knip --reporter=markdown --no-exit-code --no-progress > $GITHUB_STEP_SUMMARY
      # - run: yarn tsc
      # - run: yarn next lint
      # - run: yarn test
      # - run: yarn build
